name: plateau-docs
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - dask
  - decorator
  - msgpack-python>=0.5.2
  # Currently dask and numpy==1.16.0 clash
  - numpy!=1.15.0,!=1.16.0
  - pandas>=0.23.0,!=1.0.0
  - pyarrow>=4
  - simplejson
  - minimalkv
  - toolz
  - urlquote>=1.1.3
  - zstandard
  - attrs
  - click
  - prompt-toolkit
  - pyyaml

  # Test Code Dependencies
  - distributed
  - pytz
  - cloudpickle
  - freezegun

  # Test Framework
  - hypothesis
  - pytest>=4.5.0
  - pytest-cov
  - pytest-mock
  - setuptools_scm

  # Documentation
  - sphinx
  - jinja2<3.1
  - sphinx_rtd_theme
  - IPython
