name: Documentation CI

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'pre-commit-autoupdate'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.11.0-0
          use-mamba: true
          environment-file: docs/environment-docs.yml
          activate-environment: plateau-docs
          python-version: 3.8

      - name: List conda
        shell: bash -l {0}
        run: conda list

      - name: Build docs
        shell: bash -l {0}
        run: |
            python -m pip install --no-build-isolation --no-deps -e .
            sphinx-build -b html docs docs/_build
